name: Regression tests

on:
  push:
    branches: [ "main" ]

jobs:
  api_tests:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt
    - name: Run API Tests
      run: |
        chmod +x ./backend/run.sh
        cd backend/ && ./run.sh
    - name: Upload API Tests results
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: api-reports
        path: backend/logs
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      with:
        name: API Test results
        path: backend/logs/xunit.xml
        reporter: java-junit

  web_tests:
    needs: api_tests
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt
    - name: Run Web Tests
      run: |
        chmod +x ./frontend/run.sh
        cd frontend/ && ./run.sh
    - name: Upload Web Tests results
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: web-reports
        path: frontend/logs
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      with:
        name: Web Test results
        path: frontend/logs/xunit.xml
        reporter: java-junit